
services:
  frontend:
    depends_on:
      - backend
    build: ./frontend
    ports:
      - 3000:3000

  backend:
    build: ./backend
    ports:
      - 3001:3001

  db_pgsql:
    image: postgres:15.5-bullseye
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: scheduleCar
    ports:
      - 5432:5432
    volumes:
      - scheduleCar:/data/db

volumes:
  scheduleCar: