
services:

  frontend:
    depends_on:
      - backend
    build: ./frontend/frontend-sist-car
    container_name: frontend
    environment:
      NEXT_PUBLIC_BACKEND_URL: 'http://localhost:3000'
    ports:
      - 80:3002

  backend:
    depends_on:
      - db_pgsql
    build: ./backend/backend-sist-car
    container_name: backend
    environment:
      DB_HOST: 'db_pgsql'
      DB_PORT: 5432
      DB_USER_NAME: 'admin'
      DB_PASS: 'admin'
      DB_NAME: 'scheduleCar'
    ports:
      - 3000:3000

  db_pgsql:
    image: postgres:15.5-bullseye
    container_name: db_pgsql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: scheduleCar
    ports:
      - 5432:5432
    volumes:
      - scheduleCar:/data/db

volumes:
  scheduleCar: